### ISSUE TITLE
rake paperclipdropbox:authorize doesn't work ( 400 Bad Request )

### ISSUE THREAD

**Issue by Drasky-Vanderhoff** [dripster82/paperclipdropbox#13]
Hi i'm trying to make it work with paperclip but it doesn't give me the login url as expected, rather i get a  ( 400 Bad Request ) and not much more info than that. I had the dropboxpaperclip.yml  with the following content ( obviously replacing the elements as needed ) : 

<code>
development:
  dropbox_key: "key"
  dropbox_secret: "secret"
  path: "path"
production:
  dropbox_key: "key"
  dropbox_secret: "secret"
  path: "path"
</code>

What could be that i'm missing ? Rails 3.2.15 ,  dropbox gem 1.3.0 , paperclip 4.1.0

**Comment by KetelleP** [comment]
Version 2.0 is being released and will fix this issue.. only a few years late :D
